[package]
edition      = "2024"
name         = "entity"
publish      = false
rust-version = "1.85.0"
version      = "0.1.0"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "1.1.19"